services:
  only_forms:
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.29
    entrypoint: ""
    volumes:
      - .:/home/module
      - bundle:/home/decidim/vendor
      - node_modules:/home/decidim/node_modules
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://decidim:pleaseChangeMe@only-forms-pg:5432/decidim
      - DATABASE_HOST=only-forms-pg
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DEV_MODULE=decidim-only_forms
      - RAILS_ENV=development
      - DISABLED_DOCKER_COMPOSE=true
    depends_on:
      - only-forms-pg
    ports:
      - 3000:3000
    links:
      - only-forms-pg

  only-forms-pg:
    image: postgis/postgis:17-3.6-alpine
    volumes:
      - only-forms-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=decidim
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pleaseChangeMe

volumes:
  node_modules: {}
  bundle: {}
  only-forms-pg-data: {}
